#pragma once

#define PIN_SENSOR_ENABLE 26

#define PIN_SENSOR_LL 25
#define PIN_SENSOR_L  35
#define PIN_SENSOR_C  33
#define PIN_SENSOR_R  34
#define PIN_SENSOR_RR 32

#define PIN_MOTOR_LEFT_A 6
#define PIN_MOTOR_LEFT_B 7
#define PIN_MOTOR_LEFT_PWM 8

#define PIN_MOTOR_RIGHT_A 9
#define PIN_MOTOR_RIGHT_B 10
#define PIN_MOTOR_RIGHT_PWM 11

